# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3ee224caadbeffa955f85cfefb366ee9"
name = "shopbox"
application_url = "https://shopbox-fe.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://shopbox-api-production.up.railway.app/api/shopify/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://shopbox-api-production.up.railway.app/api/shopify/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://shopbox-api-production.up.railway.app/api/shopify/webhooks"

[access_scopes]
scopes = "read_customers,read_discounts,read_fulfillments,read_inventory,read_metaobjects,read_orders,read_price_rules,read_product_listings,read_products,read_shipping,write_customers,write_metaobjects,write_orders,write_draft_orders"

[auth]
redirect_urls = [
  "https://shopbox-api-production.up.railway.app/api/shopify/auth/callback",
  "https://shopbox-fe.vercel.app/auth/callback"
]